### ISSUE TITLE
Time Reversal

### ISSUE THREAD

**Issue by FaustsDaemon** [HatlessStudios/in-an-instant#19]
Using retrace isn't behaving as a retrace as forces oppose each other.

e.g. Try to put electrons in orbit around one another, then retrace, the particles oppose each other and fly off in different directions.

This may be a fundamental issue with how we're thinking about time.

**Comment by AlexandreTunstall** [comment]
Could not reproduce.

**Comment by AlexandreTunstall** [comment]
## Particles with positive gravity

#### Expected Behaviour

They should repel each other when inside a retrace field (think of it as being the opposite of when they're in a flow field).

#### Observed Behaviour

They repel each other as expected.

## Particles with negative charge

#### Expected Behaviour

They should attract each other when inside a retrace field (if time weren't reversed, they would repel each other).

#### Observed Behaviour

They attract each other as expected.

*****

Please describe exactly what you did, what you expected to happen, and what actually happened to make it easier for me to reproduce this issue.
